### ISSUE TITLE
Inline data declaration

### ISSUE THREAD

**Issue by mbtools** [exercism/abap-test-runner#13]
```abap
CLASS zcl_two_fer DEFINITION PUBLIC.
  PUBLIC SECTION.
    METHODS two_fer
      IMPORTING
        input         TYPE string OPTIONAL
      RETURNING
        VALUE(result) TYPE string.
ENDCLASS.

CLASS zcl_two_fer IMPLEMENTATION.

  METHOD two_fer.
    if input = ''.
      data(name) = 'you'.
    else.
      name = input.
    endif.
    result = |One for { name }, one for me.|.
  ENDMETHOD.

ENDCLASS.
```

```
ZCL_TWO_FER: running ltcl_two_fer->test_empty

ReferenceError: name is not defined
    at zcl_two_fer.two_fer (file:///tmp/exercism-abap-runner-DImz7j/compiled/zcl_two_fer.clas.mjs:19:27)
    at ltcl_two_fer.test_empty (file:///tmp/exercism-abap-runner-DImz7j/compiled/zcl_two_fer.clas.testclasses.mjs:15:88)
    at run (file:///tmp/exercism-abap-runner-DImz7j/compiled/index.mjs:69:14)
```

**Comment by larshp** [comment]
thanks, need to enable https://rules.abaplint.org/definitions_top/ too for the downport to work

**Comment by larshp** [comment]
@mbtools thanks, try again
